// <auto-generated />
using System;
using CarManaagementApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarManaagementApi.Migrations.RentX
{
    [DbContext(typeof(RentXDbContext))]
    [Migration("20260304114532_EmailVerification")]
    partial class EmailVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PickAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951AED097858AE");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationCode");

                    b.HasIndex(new[] { "CarId", "PickAt", "DropAt" }, "IX_Bookings_Car_Time");

                    b.HasIndex(new[] { "PickAt" }, "IX_Bookings_PickAt")
                        .IsDescending();

                    b.HasIndex(new[] { "Status", "LocationCode" }, "IX_Bookings_Status");

                    b.ToTable("Bookings", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Branch", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<TimeOnly>("CloseAt")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<TimeOnly>("OpenAt")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("BranchId")
                        .HasName("PK__Branches__A1682FC55422CA83");

                    b.ToTable("Branches", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Car", b =>
                {
                    b.Property<string>("CarId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Seats")
                        .HasColumnType("tinyint");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("CarId")
                        .HasName("PK__Cars__68A0342E63766721");

                    b.HasIndex(new[] { "BranchId", "IsActive" }, "IX_Cars_Branch_Active");

                    b.HasIndex(new[] { "RegNo" }, "UX_Cars_RegNo")
                        .IsUnique();

                    b.ToTable("Cars", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.CarImage", b =>
                {
                    b.Property<long>("CarImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CarImageId"));

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CarImageId")
                        .HasName("PK__CarImage__614BE6AFBBEFE911");

                    b.HasIndex(new[] { "CarId", "SortOrder" }, "IX_CarImages_CarId");

                    b.ToTable("CarImages", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("individual");

                    b.Property<DateOnly?>("DlExpiry")
                        .HasColumnType("date");

                    b.Property<string>("DlNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KycNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("KycType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D87578CBD5");

                    b.HasIndex(new[] { "Name" }, "IX_Customers_Name");

                    b.ToTable("Customers", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.MaintenanceBlock", b =>
                {
                    b.Property<string>("MaintenanceId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("BlockFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BlockTo")
                        .HasColumnType("date");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaintenanceId")
                        .HasName("PK__Maintena__E60542D5388A8CAB");

                    b.HasIndex(new[] { "CarId", "BlockFrom", "BlockTo" }, "IX_MaintenanceBlocks_Car_Date");

                    b.ToTable("MaintenanceBlocks", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1260486144");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "IX_Notifications_User_Read")
                        .IsDescending(false, false, true);

                    b.ToTable("Notifications", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspection", b =>
                {
                    b.Property<string>("InspectionId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("CleaningCharge")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("CleaningRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("FuelCharge")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte>("FuelPercent")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("LateFeePerHour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("LateHours")
                        .HasColumnType("int");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int");

                    b.Property<decimal>("Refund")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalDamage")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("InspectionId")
                        .HasName("PK__ReturnIn__30B2DC085814FBFC");

                    b.HasIndex("BookingId");

                    b.HasIndex("CarId");

                    b.ToTable("ReturnInspections", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspectionDamage", b =>
                {
                    b.Property<long>("DamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DamageId"));

                    b.Property<decimal>("EstCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DamageId")
                        .HasName("PK__ReturnIn__8A0F21625ABB127C");

                    b.HasIndex("InspectionId");

                    b.ToTable("ReturnInspectionDamages", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspectionDamagePhoto", b =>
                {
                    b.Property<long>("DamagePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DamagePhotoId"));

                    b.Property<long>("DamageId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DamagePhotoId")
                        .HasName("PK__ReturnIn__E711BCBBF88BE136");

                    b.HasIndex("DamageId");

                    b.ToTable("ReturnInspectionDamagePhotos", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleCode")
                        .HasName("PK__Roles__D62CB59D0A5C66A8");

                    b.ToTable("Roles", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("RoleCode", "ModuleName");

                    b.ToTable("RolePermissions", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C654070D8");

                    b.HasIndex("RoleCode");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.UserEmailVerification", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("VerificationId");

                    b.HasIndex("UserId", "VerificationCode")
                        .HasDatabaseName("IX_UserEmailVerifications_User_Code");

                    b.ToTable("UserEmailVerifications", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.UserRefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK__UserRefr__F5845E39CA91DC41");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "UX_UserRefreshTokens_TokenHash")
                        .IsUnique();

                    b.ToTable("UserRefreshTokens", "rentx");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Booking", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Cars");

                    b.HasOne("CarManaagementApi.Persistence.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Customers");

                    b.HasOne("CarManaagementApi.Persistence.Entities.Branch", "LocationCodeNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("LocationCode")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Branches");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("LocationCodeNavigation");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Car", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Branch", "Branch")
                        .WithMany("Cars")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Cars_Branches");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.CarImage", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Car", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK_CarImages_Cars");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.MaintenanceBlock", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Car", "Car")
                        .WithMany("MaintenanceBlocks")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceBlocks_Cars");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Notification", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspection", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Booking", "Booking")
                        .WithMany("ReturnInspections")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnInspections_Bookings");

                    b.HasOne("CarManaagementApi.Persistence.Entities.Car", "Car")
                        .WithMany("ReturnInspections")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnInspections_Cars");

                    b.Navigation("Booking");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspectionDamage", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.ReturnInspection", "Inspection")
                        .WithMany("ReturnInspectionDamages")
                        .HasForeignKey("InspectionId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnInspectionDamages_Inspections");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspectionDamagePhoto", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.ReturnInspectionDamage", "Damage")
                        .WithMany("ReturnInspectionDamagePhotos")
                        .HasForeignKey("DamageId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnInspectionDamagePhotos_Damages");

                    b.Navigation("Damage");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.RolePermission", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Role", "RoleCodeNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleCode")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("RoleCodeNavigation");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.User", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.Role", "RoleCodeNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleCode")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("RoleCodeNavigation");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.UserEmailVerification", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.User", "User")
                        .WithMany("UserEmailVerifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserEmailVerifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("CarManaagementApi.Persistence.Entities.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Booking", b =>
                {
                    b.Navigation("ReturnInspections");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CarImages");

                    b.Navigation("MaintenanceBlocks");

                    b.Navigation("ReturnInspections");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspection", b =>
                {
                    b.Navigation("ReturnInspectionDamages");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.ReturnInspectionDamage", b =>
                {
                    b.Navigation("ReturnInspectionDamagePhotos");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarManaagementApi.Persistence.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("UserEmailVerifications");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
